### ISSUE TITLE
Please add Browser Compatibility to ReadMe

### ISSUE THREAD

**Issue by stongey-esri-ca** [Esri/workflowmanager-viewer-js#4]
We tried to deploy this at a client site and could not get it to work. It failed during the login. Eventually we realized that it worked with Chrome, IE10 and IE 11, but not with the client's IE9 computers.

The ArcGIS JavaScript API (3.16) supports back to IE 7. There is some code in the index.html to error for IE8.

The requirement is fine since these are old browsers, but would be nice to see it in the doc.

**Comment by llam001** [comment]
The README was updated in March when this issue was submitted.
