### ISSUE TITLE
Unable to Login with AD

### ISSUE THREAD

**Issue by danielkmog** [Esri/workflowmanager-viewer-js#7]
I'm attempting to setup our Workflow Manager JavaScript site with AD logins. We're currently using SSO for Portal and AGS with no issues. I was able to login with authentication set to 'none'.

I've modified the following lines of code as directed and have also tried the text call-outs to see the variable, but it's not working. It reads back <%= User.Identity.Name %> and not the Windows User.

```
        var user = "<%= User.Identity.Name.Replace("MyDomain\","") %>";  // user without domain authentication
        //var user = "<%= User.Identity.Name.Replace("\","*") %>";     // user with domain authentication
        Controller.startup( {user: user} );
```

Has anyone else had this issue? Thank you.

**Comment by llam001** [comment]
@danielkmog - It sounds like you've setup a [portal and federated server to use Windows accounts](http://server.arcgis.com/en/portal/latest/administer/windows/setting-up-your-portal-and-federated-server-to-use-windows-accounts.htm).  If this is the case, then you will need to following the instructions in the [JavaScript Viewer README.pdf](https://github.com/Esri/workflowmanager-viewer-js/blob/master/README.pdf) file for setting up Portal Authentication.  

Let us know if this works for you.

Thanks,
Lalaine

**Comment by danielkmog** [comment]
Thank you. I was able to get it working. I was missing the rename of the index.html and .config steps. The portal is federated, but we're hosting our Portal on site and I wasn't able to configure WMX 10.4.1 to use our Portal user store, it's asking for a AGOL login and I do not see a way to point it to our store.  I'll look into a work around later for now I'll just use AD.

**Comment by kbedel** [comment]
@danielkmog - I'm glad you were able to get your issue resolved. If you are still wanting to get it to work with the Portal user store, you can change the Portal by using the ArcGIS Administrator utility. This is because Workflow Manager 10.4.1 uses the same Portal as ArcMap, ArcCatalog, etc.

The [Managing portal connections from ArcGIS for Desktop](http://desktop.arcgis.com/en/arcmap/10.4/get-started/administer/managing-portal-connections-from-arcgis-for-desktop.htm) document provides more help on this.

**Comment by danielkmog** [comment]
@kbedel I was just trying to do that. I set it up via the ArcGIS administrator, go into the WMX admin, change it to Portal and it toggles automatically back to Traditional. Getting ready to call Esri. 🤔
