### ISSUE TITLE
TypeError: Cannot read property 'slider' of undefined

### ISSUE THREAD

**Issue by MelisaM** [Esri/workflowmanager-viewer-js#9]
![capture1](https://user-images.githubusercontent.com/12767165/33963390-61ae3612-e01a-11e7-9542-2201494ce407.JPG)
![capture2](https://user-images.githubusercontent.com/12767165/33963391-61c9b928-e01a-11e7-9dde-6bfe30666582.JPG)

I'm using JavaScript API 3.19, Workflow manager 10.5.1, SDE database 10.5.1, ArcGIS Server 10.3.1.  Not sure if this error is due to Server 10.3.1 needing upgraded or something else?

Could anyone please provide suggestions?

Thanks!

**Comment by llam001** [comment]
Hi Melisa,

What version of the Workflow Manager JavaScript viewer are you using?  If you're using ArcGIS Server 10.3.1, you should be using the [10.3.1 version of the Workflow Manager JavaScript viewer](https://github.com/Esri/workflowmanager-viewer-js/tree/10.3.1).

The error you're seeing is coming from initializing the map.  You should have a  navigation `slider` property in your [`AppConfig.js`](https://github.com/Esri/workflowmanager-viewer-js/blob/master/js/app/WorkflowManager/config/AppConfig.js) file.  If ithe slider is not needed, you'll need to set `isEnabled` to `false`.

Example:
```
navigation: {
   slider: {
      isEnabled: false,
```

Hope that helps.

**Comment by MelisaM** [comment]
Thanks!  I needed a reason to upgrade our server installation!

Appreciate your help!

Melisa M. McLean
GIS Manager
St. Louis County GIS Service Center
41 S Central Ave, 3rd Fl
Clayton, MO 63105
314.615.3899
mmclean@stlouisco.com<mailto:mmclean@stlouisco.com>
http://data.stlouisco.com
